project_id = "gtbdralyuxnpqbinakib"

[functions.conflict-suggestion]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.predict-delays]
verify_jwt = false

[functions.forecast-congestion]
verify_jwt = false
